// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iglkrwpruybqmdtqijet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlnbGtyd3BydXlicW1kdHFpamV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMzODg1MDAsImV4cCI6MjA3ODk2NDUwMH0.gdsS3I8NYS5fJb-My_Pq08yL_2kXLZQYK_ut_1DAauM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});